"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
OPTIONS = dict(
    argv_emulation=True,
    frameworks=['libavbin.dylib','pymunk/libchipmunk.dylib'],
    plist = dict(CFBundleIconFile='gw0rp.icns')#, PyRuntimeLocations=['/Library/Frameworks/Python.framework/Versions/Current/Python', '/System/Library/Frameworks/Python.framework/Versions/Current/Python'])
)

setup(
    app=['gw0rp.py'],
    data_files=['Data','gamelib','lepton',
                'pymunk','psyco','gw0rp.icns', 'yaml', 'pyglet'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
