"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
OPTIONS = dict(
    argv_emulation=True,
    frameworks=['libavbin.dylib'],
    includes=['yaml','pyglet']
)

setup(
    app=['gw0rp_level_editor.py'],
    data_files=['Editor','leveleditorlibs','Data'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
